### PR TITLE
Update Travis setup

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@cdwensley Would you also please consider making a release of this package (which would be very, very minor, say version 1.67.1)? There is just one commit not in 1.67, namely the one saying "fixed errors in tests introduced by gapdev". Since this is not released, it'll fail on our CI servers, distracting from "real" failures.

**Comment by cdwensley** [comment]
After merging and pulling, most of the changes to .travis.yml were made, but the new line 24 still had "bash" in it.  Have now edited that locally to become "  - scripts/gather-coverage.sh". Very odd.

**Comment by cdwensley** [comment]
My mistake - comes of addressing PRs in Utils and Groupoids simultaneously.  No doubt the new version of .travis.yml should be used in all the Bangor packages.

**Comment by cdwensley** [comment]
Version 1.68 released

**Pull request merged**
